services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file: ".env"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/prod_db_init:/docker-entrypoint-initdb.d
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/lib/postgresql/data/.initialized && pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   ports:
  #     - "1025:1025"   # SMTP
  #     - "8025:8025"   # Web UI
  #   environment:
  #     MH_STORAGE: maildir
  #   networks:
  #     - app-net

  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ".env"
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
