services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file: ".env"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/prod_db_init:/docker-entrypoint-initdb.d:Z
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/lib/postgresql/data/.initialized && pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      otel-collector:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file: ".env"
    networks:
      - app-net
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.0
    container_name: otel_collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:Z,ro
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      app-net:
        aliases:
          - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686" # UI
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
