services:
  postgres:
    image: postgres:15-alpine
    container_name: "${POSTGRES_CONTAINER_NAME:-postgres_db}"
    cpuset: "${POSTGRES_CPUSET:-3-7}"
    mem_limit: 8g
    env_file: ".env"
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${HOST_POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/prod_db_init:/docker-entrypoint-initdb.d:Z
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/lib/postgresql/data/.initialized && pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  app:
    build: .
    container_name: "${APP_CONTAINER_NAME:-go_app}"
    ports:
      - "${HOST_APP_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    cpuset: "${APP_CPUSET:-8-9}"
    mem_limit: 4g
    env_file: ".env"
    environment:
      ADDR: :8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cinema
      DB_USER: postgres
      DB_PASS: postgres
      DB_SSL: disable
      TEST_DB_NAME: cinema_test
      JWT_SECRET: secret-key
      TOKEN_DURATION: 24h
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge
